

import java.util.*;
import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.util.Date;
public class Publisher extends javax.swing.JFrame {
    
    private Connection conn = null;
    private PreparedStatement pst = null;
    private ResultSet rs = null;
    private String email="";
    private String comp;
    public Publisher() {
        setResizable(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFyllo = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblJournalists = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        comboFyllo = new javax.swing.JComboBox<>();
        btnSubmit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSettings = new javax.swing.JButton();
        lblHello = new javax.swing.JLabel();
        btnSignOut = new javax.swing.JButton();
        spinnerNO = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblChief = new javax.swing.JLabel();
        lblFrequency = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNewName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        spinnerNewFrequency = new javax.swing.JSpinner();
        comboNewChief = new javax.swing.JComboBox<>();
        btnSetNewName = new javax.swing.JButton();
        btnSetNewFrequency = new javax.swing.JButton();
        btnSetNewChief = new javax.swing.JButton();

        jLabel11.setText("jLabel11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrator");

        tblFyllo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NO", "Copies", "Sold", "State ", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblFyllo);

        tblJournalists.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Surname", "Email", "Job"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblJournalists.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblJournalistsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblJournalists);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Copies:");

        btnSubmit.setBackground(new java.awt.Color(51, 153, 255));
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("NO OF COPIES");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PaperNO");

        btnSettings.setBackground(new java.awt.Color(51, 153, 255));
        btnSettings.setText("SETTINGS");
        btnSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettingsActionPerformed(evt);
            }
        });

        lblHello.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblHello.setForeground(new java.awt.Color(255, 0, 51));
        lblHello.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblHello.setText("WELCOME");

        btnSignOut.setBackground(new java.awt.Color(51, 153, 255));
        btnSignOut.setText("SIGN OUT");
        btnSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignOutActionPerformed(evt);
            }
        });

        spinnerNO.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("MODIFY COMPANY");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 51));
        jLabel5.setText("NEWSPAPER");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("NewPaper Name:");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Chief editor:");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Frequency of publication:");

        lblName.setForeground(new java.awt.Color(255, 255, 255));

        lblChief.setForeground(new java.awt.Color(255, 255, 255));

        lblFrequency.setForeground(new java.awt.Color(255, 255, 255));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("New name:");

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("New Frequency:");

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("New Chief:");

        spinnerNewFrequency.setModel(new javax.swing.SpinnerNumberModel(1, 1, 30, 1));

        btnSetNewName.setBackground(new java.awt.Color(51, 153, 255));
        btnSetNewName.setText("SET");
        btnSetNewName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetNewNameActionPerformed(evt);
            }
        });

        btnSetNewFrequency.setBackground(new java.awt.Color(51, 153, 255));
        btnSetNewFrequency.setText("SET");
        btnSetNewFrequency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetNewFrequencyActionPerformed(evt);
            }
        });

        btnSetNewChief.setBackground(new java.awt.Color(51, 153, 255));
        btnSetNewChief.setText("SET");
        btnSetNewChief.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetNewChiefActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHello, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnSignOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(125, 125, 125)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblChief, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                    .addComponent(lblFrequency, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(48, 48, 48)
                                        .addComponent(txtNewName))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(comboNewChief, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(spinnerNewFrequency, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSetNewFrequency, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                    .addComponent(btnSetNewChief, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSetNewName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(comboFyllo, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(spinnerNO, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHello, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSignOut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)))
                .addComponent(btnSettings)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblChief, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(lblFrequency, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtNewName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSetNewName))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboFyllo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(spinnerNewFrequency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSetNewFrequency))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinnerNO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(comboNewChief, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSetNewChief))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSubmit)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        String sql = "UPDATE fyllo SET fyl_antitypa = ? WHERE fyl_efhmerida=? AND fyl_arithmos=?";
        try{
            if(comboFyllo.getSelectedItem() != null){
                pst=conn.prepareStatement(sql);
                pst.setString(1, spinnerNO.getValue().toString());
                pst.setString(2, comp);
                pst.setString(3, comboFyllo.getSelectedItem().toString());
                pst.executeUpdate();
                setAndRefresh();
                JOptionPane.showMessageDialog(null, "Successful submittion!");
            }
            else{
                JOptionPane.showMessageDialog(null, "No available paper!");
            }
        }catch(Exception ex){JOptionPane.showMessageDialog(null, ex);}
        
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingsActionPerformed
        Settings s = new Settings();
        s.setInfo(email, comp);
        s.setVisible(true);
    }//GEN-LAST:event_btnSettingsActionPerformed

    private void btnSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignOutActionPerformed
        setVisible(false);
        Login_GUI l = new Login_GUI();
        l.setVisible(true);
    }//GEN-LAST:event_btnSignOutActionPerformed

    private void tblJournalistsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblJournalistsMouseClicked
           int index = tblJournalists.getSelectedRow();
           TableModel model = tblJournalists.getModel();
           String temp_email = model.getValueAt(index, 2).toString();
           JOptionPane.showMessageDialog(null, "Email: "+temp_email);
    }//GEN-LAST:event_tblJournalistsMouseClicked

    private void btnSetNewNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetNewNameActionPerformed
        int reply = JOptionPane.showConfirmDialog(null, "Are you sure?");
        if (reply == JOptionPane.YES_OPTION){
        if(!txtNewName.getText().equals("")){
            String sql = "UPDATE efhmerida SET efh_onoma=? WHERE efh_onoma=?";
            
            try{
                //UPDATE TABLE EFHMERIDA
                pst = conn.prepareCall(sql);
                pst.setString(1, txtNewName.getText());
                pst.setString(2, comp);
                pst.executeUpdate();
                comp = txtNewName.getText();
                setTitle(comp);
                JOptionPane.showMessageDialog(null, "Successful change!");
                txtNewName.setText("");
                setAndRefresh();
            }
            catch(Exception ex){JOptionPane.showMessageDialog(null, "There cant be 2 NewsPaper with the same Name!");}
        }
        else{
            JOptionPane.showMessageDialog(null, "NewsPaper name can not be empty!");
        }
    }
    }//GEN-LAST:event_btnSetNewNameActionPerformed

    private void btnSetNewFrequencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetNewFrequencyActionPerformed
        String sql = "UPDATE efhmerida SET efh_syxnothta_ekdoshs=? WHERE efh_onoma=?";
        try{
            pst = conn.prepareStatement(sql);
            pst.setString(1, spinnerNewFrequency.getValue().toString());
            pst.setString(2, comp);
            pst.executeUpdate();
            lblFrequency.setText(spinnerNewFrequency.getValue().toString());
            spinnerNewFrequency.setValue(1);
            JOptionPane.showMessageDialog(null, "Successful change");
        }
        
        catch(Exception ex){JOptionPane.showMessageDialog(null, ex);}
    }//GEN-LAST:event_btnSetNewFrequencyActionPerformed

    private void btnSetNewChiefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetNewChiefActionPerformed
        int reply = JOptionPane.showConfirmDialog(null, "Are you sure?");
        if(reply == JOptionPane.YES_OPTION){
            String sql = "SELECT * FROM diaxirizetai WHERE dia_onoma=?";
            String sql1 = "UPDATE dimosiografos SET dim_idiothta=? WHERE dim_email=?";
            String sql2 = "UPDATE login SET property=? WHERE email=?";
            String sql3 = "UPDATE diaxirizetai SET dia_email=? WHERE dia_onoma=?";
            try{
            String temp_email = "";
            //TAKE OLD CHIEFS EMAIL
            pst = conn.prepareStatement(sql);
            pst.setString(1, comp);
            rs = pst.executeQuery();
            if(rs.next()){
                temp_email = rs.getString("dia_email");
            }
            
            //SETS OLD CHIEF -----> JOURNALIST
            pst = conn.prepareStatement(sql1);
            pst.setString(1, "Dimosiografos");
            pst.setString(2, temp_email);
            pst.executeUpdate();
                    
            pst = conn.prepareStatement(sql2);
            pst.setString(1, "Journalist");
            pst.setString(2, temp_email);
            pst.executeUpdate();
            
            //SETS JOUNALIST -----> NEW CHIEF
            pst = conn.prepareStatement(sql1);
            pst.setString(1, "Arxisintakths");
            pst.setString(2, comboNewChief.getSelectedItem().toString());
            pst.executeUpdate();
            
            pst = conn.prepareStatement(sql2);
            pst.setString(1, "Chief");
            pst.setString(2, comboNewChief.getSelectedItem().toString());
            pst.executeUpdate();
            
            //SETS IT TO TABLE DIAXIRIZETAI
            pst = conn.prepareStatement(sql3);
            pst.setString(1, comboNewChief.getSelectedItem().toString());
            pst.setString(2, comp);
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Successful Update!");
            setAndRefresh();
            
            
        }
        catch(Exception ex){JOptionPane.showMessageDialog(null, ex);}
            
        }
        
        
        
    }//GEN-LAST:event_btnSetNewChiefActionPerformed

    public void setInfo(Connection con, String company){
        this.conn = con;
        this.comp = company;
    }
    
    private void showFylla() throws ParseException{
        String sql = "SELECT * FROM fyllo WHERE fyl_efhmerida=?";
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String temp = sdf.format(new Date());
        Date current_date = sdf.parse(temp);
        String temp1;
        Date date2;
        DefaultTableModel model = (DefaultTableModel)tblFyllo.getModel();
        Object[] row = new Object[5];
        model.setRowCount(0);
        try{
            pst = conn.prepareStatement(sql);
            pst.setString(1, comp);
            rs = pst.executeQuery();
            while(rs.next()){
                temp1 = rs.getString("fyl_kikloforia");
                date2 = sdf.parse(temp1);
                row[0] = rs.getInt("fyl_arithmos");
                row[1] = rs.getInt("fyl_antitypa");
                if(current_date.compareTo(date2) >= 0 ){
                    int temp_epistramena = rs.getInt("fyl_epistramena_antit");
                    int temp_copies = rs.getInt("fyl_antitypa");
                    if(temp_epistramena == -1){
                        row[2] = "-";
                    }
                    else{
                        row[2] = temp_copies - temp_epistramena;
                    }
                }
                else{
                    row[2] = "-";
                }
                if(current_date.compareTo(date2) >= 0){
                        row[3] = "Published";
                }
                else{
                    comboFyllo.addItem(rs.getString("fyl_arithmos")); //set COMBO FYLLO
                    row[3] = "Editable";
                }
                row[4] = rs.getDate("fyl_kikloforia");
                
                    
                model.addRow(row);
                
                    
                
            }
        }
        catch(Exception e){JOptionPane.showMessageDialog(null, e);}
        
    }
    
    private void showPeople(){
        String sql = "SELECT * FROM dimosiografos WHERE dim_efhmerida=?";
        String sql1 = "SELECT * FROM dioikitikos WHERE dik_efhmerida=?";
        DefaultTableModel model = (DefaultTableModel)tblJournalists.getModel();
        Object[] row = new Object[4];
        model.setRowCount(0);
        try{
            pst = conn.prepareStatement(sql);//journalists----------
            pst.setString(1, comp);
            rs = pst.executeQuery();
            while(rs.next()){
                row[0] = rs.getString("dim_onoma");
                row[1] = rs.getString("dim_epitheto");
                row[2] = rs.getString("dim_email");
                if(rs.getString("dim_idiothta").equals("Arxisintakths")){
                    row[3] = "Chief";
                }
                else{
                    comboNewChief.addItem(rs.getString("dim_email"));
                    row[3] = "Journalist";
                }
                
                model.addRow(row);
            }
            pst = conn.prepareStatement(sql1);//administrators----------
            pst.setString(1, comp);
            rs = pst.executeQuery();
            while(rs.next()){
                row[0] = rs.getString("dik_onoma");
                row[1] = rs.getString("dik_epitheto");
                row[2] = rs.getString("dik_email");
                row[3] = rs.getString("dik_kathikonta");
                model.addRow(row);
            }
        }
        catch(Exception e){JOptionPane.showMessageDialog(null, e);}
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrative.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrative.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrative.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrative.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrative().setVisible(true);
            }
        });
    }
    
    public void initialize(String username) throws ParseException{
        lblHello.setText("Welcome "+username);
        tblFyllo.getColumnModel().getColumn(0).setPreferredWidth(40);
        setAndRefresh();
    }
    
    private void setAndRefresh() throws ParseException{
        comboNewChief.removeAllItems();
        lblName.setText(comp);
        String sql = "SELECT * FROM diaxirizetai WHERE dia_onoma=?";
        String sql1 = "SELECT * FROM efhmerida WHERE efh_onoma=?";
        String sql2 = "SELECT * FROM dimosiografos WHERE dim_email=?";
        String temp_email="";
        try{
            //TAKES CHIEFS EMAIL
            pst = conn.prepareStatement(sql);
            pst.setString(1, comp);
            rs = pst.executeQuery();
            if(rs.next()){
                temp_email = rs.getString("dia_email");
            }
            
            //TAKES CHIEFS NAME AND SURNAME
            pst = conn.prepareStatement(sql2);
            pst.setString(1, temp_email);
            rs = pst.executeQuery();
            if(rs.next()){
                lblChief.setText(rs.getString("dim_onoma")+" "+rs.getString("dim_epitheto"));
            }
            
            //TAKES FREQUENCY
            pst = conn.prepareStatement(sql1);
            pst.setString(1, comp);
            rs = pst.executeQuery();
            
            if(rs.next()){
                lblFrequency.setText(rs.getString("efh_syxnothta_ekdoshs"));
            }
        }
        catch(Exception ex){JOptionPane.showMessageDialog(null, ex);}
        comboFyllo.removeAllItems();
        showFylla(); //set TABLE FYLLO and COMBO FYLLO
        showPeople();//set TABLE SALARY
        
        
        
     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSetNewChief;
    private javax.swing.JButton btnSetNewFrequency;
    private javax.swing.JButton btnSetNewName;
    private javax.swing.JButton btnSettings;
    private javax.swing.JButton btnSignOut;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> comboFyllo;
    private javax.swing.JComboBox<String> comboNewChief;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblChief;
    private javax.swing.JLabel lblFrequency;
    private javax.swing.JLabel lblHello;
    private javax.swing.JLabel lblName;
    private javax.swing.JSpinner spinnerNO;
    private javax.swing.JSpinner spinnerNewFrequency;
    private javax.swing.JTable tblFyllo;
    private javax.swing.JTable tblJournalists;
    private javax.swing.JTextField txtNewName;
    // End of variables declaration//GEN-END:variables
}
